In [3]:
import pandas as pd
import numpy as np 
import keras 
from keras import models
from keras.models import Model
from keras.layers import*
from keras import optimizers
from sklearn.model_selection import train_test_split

In [4]:
df_train = pd.read_csv("mnist_train.csv")
df_test = pd.read_csv("mnist_test.csv")

In [5]:
df_train.shape

(60000, 785)

In [6]:
df_test.shape

(10000, 785)

In [7]:
df_features = df_train.iloc[:,1:785]

In [8]:
df_lables = df_train.iloc[:,0]

In [9]:
df_lables

0        5
1        0
2        4
3        1
4        9
        ..
59995    8
59996    3
59997    5
59998    6
59999    8
Name: label, Length: 60000, dtype: int64

In [10]:
df_features

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
X_test = df_test.iloc[:,0:784]

In [12]:
X_test

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x18,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
print(X_test.shape)

(10000, 784)

In [14]:
# X_train,X_cv,y_train,y_cv=train_test_split(
#     df_features,df_lables,
#     random_state=1212,
#     test_size = 0.2
# )

# #there is no need to do the reshaping 
# X_train = X_train.to_numpy()
# X_cv = X_cv.to_numpy()
# #X_test = X_test.to_numpy()    this is already in the numpy array

In [15]:
# print(min(X_train[0]),max(X_train[1]))

In [16]:
# #Feature Normalization
# X_train = X_train.astype("float");X_cv = X_cv.astype("float");X_test = X_test.astype("float")
# X_train /= 255
# X_cv /= 255
# X_test /= 255

# #Conver lables into one hot encoded
# num_digit = 10
# y_train = keras.utils.to_categorical(y_train,num_digit)
# y_cv = keras.utils.to_categorical(y_cv,num_digit)

In [17]:
##new train
X_train, X_cv, y_train, y_cv = train_test_split(
    df_features,
    df_lables,
    random_state=1212,
    test_size=0.2
)

X_train = X_train.to_numpy().astype("float32")
X_cv = X_cv.to_numpy().astype("float32")
X_test = X_test.astype("float32")   # if already numpy

X_train /= 255.0
X_cv /= 255.0
X_test /= 255.0
# #Conver lables into one hot encoded
num_digit = 10
y_train = keras.utils.to_categorical(y_train,num_digit)
y_cv = keras.utils.to_categorical(y_cv,num_digit)

In [18]:
#printing after encoding
print(y_train[6])
print(y_train[5])

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

In [19]:
#input parameter
n_input = 784
n_hidden1 = 300
n_hidden2= 100
n_hidden3 = 100
n_hidden4 = 200
num_digit = 10

In [20]:
inp = Input(shape=(784,))
x = Dense(n_hidden1, activation= "relu", name="hidden_layer_1")(inp)
x = Dense(n_hidden2, activation= "relu", name="hidden_layer_2")(x)
x = Dense(n_hidden3, activation= "relu", name="hidden_layer_3")(x)
x = Dense(n_hidden4, activation= "relu", name="hidden_layer_4")(x)
output = Dense(num_digit, activation= "softmax", name="Output_layer")(x)

In [21]:
model = Model(inp,output)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_layer_4 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 297,910 (1.14 MB)

 Trainable params: 297,910 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
#inserting the hyperparameter
learning_rate= 0.001
batch_size = 100
training_epochs = 20
sgd = optimizers.SGD(learning_rate=learning_rate)

In [23]:
#Compile the model
model.compile(loss = "categorical_crossentropy",
             optimizer = sgd,
             metrics = ["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [24]:
history1 = model.fit(
    X_train,y_train,
    batch_size= batch_size,
    epochs = training_epochs,
    verbose = 2,
    validation_data = (X_cv,y_cv)
)

Epoch 1/20
480/480 - 3s - 7ms/step - accuracy: 0.1399 - loss: 2.2731 - val_accuracy: 0.2011 - val_loss: 2.2391
Epoch 2/20
480/480 - 3s - 5ms/step - accuracy: 0.2695 - loss: 2.2001 - val_accuracy: 0.3382 - val_loss: 2.1552
Epoch 3/20
480/480 - 2s - 5ms/step - accuracy: 0.4059 - loss: 2.0954 - val_accuracy: 0.4717 - val_loss: 2.0257
Epoch 4/20
480/480 - 2s - 5ms/step - accuracy: 0.5264 - loss: 1.9319 - val_accuracy: 0.5744 - val_loss: 1.8256
Epoch 5/20
480/480 - 2s - 5ms/step - accuracy: 0.6177 - loss: 1.6932 - val_accuracy: 0.6514 - val_loss: 1.5527
Epoch 6/20
480/480 - 2s - 5ms/step - accuracy: 0.6901 - loss: 1.4024 - val_accuracy: 0.7228 - val_loss: 1.2571
Epoch 7/20
480/480 - 2s - 5ms/step - accuracy: 0.7464 - loss: 1.1273 - val_accuracy: 0.7592 - val_loss: 1.0102
Epoch 8/20
480/480 - 2s - 5ms/step - accuracy: 0.7780 - loss: 0.9190 - val_accuracy: 0.7828 - val_loss: 0.8378
Epoch 9/20
480/480 - 2s - 5ms/step - accuracy: 0.8001 - loss: 0.7789 - val_accuracy: 0.8055 - val_loss: 0.7232
Epoch 10/20
480/480 - 2s - 5ms/step - accuracy: 0.8189 - loss: 0.6842 - val_accuracy: 0.8184 - val_loss: 0.6440
Epoch 11/20
480/480 - 2s - 5ms/step - accuracy: 0.8329 - loss: 0.6165 - val_accuracy: 0.8347 - val_loss: 0.5846
Epoch 12/20
480/480 - 2s - 5ms/step - accuracy: 0.8453 - loss: 0.5655 - val_accuracy: 0.8462 - val_loss: 0.5385
Epoch 13/20
480/480 - 3s - 5ms/step - accuracy: 0.8553 - loss: 0.5253 - val_accuracy: 0.8563 - val_loss: 0.5023
Epoch 14/20
480/480 - 3s - 6ms/step - accuracy: 0.8641 - loss: 0.4930 - val_accuracy: 0.8628 - val_loss: 0.4723
Epoch 15/20
480/480 - 2s - 5ms/step - accuracy: 0.8712 - loss: 0.4665 - val_accuracy: 0.8692 - val_loss: 0.4476
Epoch 16/20
480/480 - 2s - 5ms/step - accuracy: 0.8765 - loss: 0.4443 - val_accuracy: 0.8747 - val_loss: 0.4273
Epoch 17/20
480/480 - 2s - 5ms/step - accuracy: 0.8811 - loss: 0.4258 - val_accuracy: 0.8797 - val_loss: 0.4098
Epoch 18/20
480/480 - 2s - 5ms/step - accuracy: 0.8850 - loss: 0.4099 - val_accuracy: 0.8839 - val_loss: 0.3954
Epoch 19/20
480/480 - 2s - 5ms/step - accuracy: 0.8887 - loss: 0.3963 - val_accuracy: 0.8873 - val_loss: 0.3816
Epoch 20/20
480/480 - 2s - 5ms/step - accuracy: 0.8915 - loss: 0.3843 - val_accuracy: 0.8908 - val_loss: 0.3701

In [25]:
#Building 2nd model

In [26]:
#Always have to run this after the creation of 1 model beacuse to build another model it still have the previous model memory
#and this line clears the memort
from keras import backend as K
K.clear_session()

WARNING:tensorflow:From C:\Users\susha\AppData\Roaming\Python\Python313\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

In [27]:
inp = Input(shape=(784,))
x = Dense(n_hidden1, activation= "relu", name="hidden_layer_1")(inp)
x = Dense(n_hidden2, activation= "relu", name="hidden_layer_2")(x)
x = Dense(n_hidden3, activation= "relu", name="hidden_layer_3")(x)
x = Dense(n_hidden4, activation= "relu", name="hidden_layer_4")(x)
output = Dense(num_digit, activation= "softmax", name="Output_layer")(x)

In [28]:
adm = keras.optimizers.Adam(learning_rate = learning_rate)
model2 = Model(inp,output)
#Compile the model
model2.compile(loss = "categorical_crossentropy",
             optimizer = adm,
             metrics = ["accuracy"])

In [29]:
history2 = model2.fit(
    X_train,y_train,
    batch_size= batch_size,
    epochs = training_epochs,
    verbose = 2,
    validation_data = (X_cv,y_cv)
)

Epoch 1/20
480/480 - 4s - 9ms/step - accuracy: 0.9137 - loss: 0.2919 - val_accuracy: 0.9637 - val_loss: 0.1208
Epoch 2/20
480/480 - 3s - 6ms/step - accuracy: 0.9657 - loss: 0.1116 - val_accuracy: 0.9704 - val_loss: 0.0916
Epoch 3/20
480/480 - 3s - 6ms/step - accuracy: 0.9765 - loss: 0.0741 - val_accuracy: 0.9748 - val_loss: 0.0834
Epoch 4/20
480/480 - 3s - 6ms/step - accuracy: 0.9828 - loss: 0.0547 - val_accuracy: 0.9772 - val_loss: 0.0766
Epoch 5/20
480/480 - 3s - 6ms/step - accuracy: 0.9854 - loss: 0.0439 - val_accuracy: 0.9762 - val_loss: 0.0822
Epoch 6/20
480/480 - 3s - 6ms/step - accuracy: 0.9893 - loss: 0.0332 - val_accuracy: 0.9716 - val_loss: 0.0946
Epoch 7/20
480/480 - 3s - 6ms/step - accuracy: 0.9902 - loss: 0.0311 - val_accuracy: 0.9749 - val_loss: 0.0850
Epoch 8/20
480/480 - 3s - 6ms/step - accuracy: 0.9912 - loss: 0.0278 - val_accuracy: 0.9801 - val_loss: 0.0801
Epoch 9/20
480/480 - 3s - 6ms/step - accuracy: 0.9927 - loss: 0.0222 - val_accuracy: 0.9801 - val_loss: 0.0774
Epoch 10/20
480/480 - 3s - 6ms/step - accuracy: 0.9930 - loss: 0.0219 - val_accuracy: 0.9792 - val_loss: 0.0836
Epoch 11/20
480/480 - 3s - 6ms/step - accuracy: 0.9952 - loss: 0.0158 - val_accuracy: 0.9782 - val_loss: 0.0855
Epoch 12/20
480/480 - 3s - 6ms/step - accuracy: 0.9936 - loss: 0.0207 - val_accuracy: 0.9788 - val_loss: 0.0872
Epoch 13/20
480/480 - 3s - 6ms/step - accuracy: 0.9947 - loss: 0.0168 - val_accuracy: 0.9792 - val_loss: 0.0810
Epoch 14/20
480/480 - 3s - 6ms/step - accuracy: 0.9942 - loss: 0.0175 - val_accuracy: 0.9803 - val_loss: 0.0838
Epoch 15/20
480/480 - 3s - 6ms/step - accuracy: 0.9961 - loss: 0.0128 - val_accuracy: 0.9793 - val_loss: 0.0912
Epoch 16/20
480/480 - 3s - 6ms/step - accuracy: 0.9948 - loss: 0.0157 - val_accuracy: 0.9790 - val_loss: 0.0916
Epoch 17/20
480/480 - 3s - 6ms/step - accuracy: 0.9958 - loss: 0.0129 - val_accuracy: 0.9827 - val_loss: 0.0830
Epoch 18/20
480/480 - 3s - 6ms/step - accuracy: 0.9966 - loss: 0.0114 - val_accuracy: 0.9800 - val_loss: 0.0915
Epoch 19/20
480/480 - 3s - 6ms/step - accuracy: 0.9967 - loss: 0.0111 - val_accuracy: 0.9822 - val_loss: 0.0863
Epoch 20/20
480/480 - 3s - 6ms/step - accuracy: 0.9974 - loss: 0.0082 - val_accuracy: 0.9812 - val_loss: 0.0966

In [30]:
print(X_train.min(), X_train.max())
print(y_train.shape)
print(y_train[:5])

0.0 1.0
(48000, 10)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [31]:
print(df_features.max().max())
print(df_features.min().min())

255
0

In [32]:
batch_size

100